### ISSUE TITLE
Package still maintained?

### ISSUE THREAD

**Issue by dandv** [sergeyt/meteor-d3#1]
Looks like there are actively maintained wraps of the d3 library, like https://atmospherejs.com/garrilla/d3

If you'd like to hide this package from Atmosphere, while still letting apps install it, you can run

```
meteor admin set-unmigrated sergeyt:d3
```

Thanks! This will help users who search Atmosphere easily find the most current packages.

**Comment by mizzao** [comment]
Damn, it is very hard to figure out which community is an updated version of d3 now that they stopped updating it in core.

**Comment by sergeyt** [comment]
unmigrated this package!

**Comment by mizzao** [comment]
@dandv `garilla:d3` looks like it just appeared recently too, and might not be that stable. What are you suggesting as the most actively maintained d3 to use? Otherwise I'm considering starting my own...

For example, he did [this](https://github.com/garrilla/d3/commit/635a0e1e882d6a35e98eea791bfae3b6b9922bca) instead of using `api.export`.

**Comment by dandv** [comment]
@mizzao: I've started working with authors of popular libraries to integrate Meteor support directly. So far, we have:
- [Moment](https://github.com/moment/moment/pull/2059)
- [Hammer](https://github.com/hammerjs/hammer.js/pull/724) - ~10k GitHub stars
- [Sortable](https://github.com/RubaXa/Sortable/pull/115) - canonical example of the integration PR

Work is tracked at https://github.com/raix/Meteor-community-discussions/issues/14

It'd be great of we got @mbostock to accept a PR like that, and have only _one_ integration on which Meteor devs can work.

**Comment by mizzao** [comment]
What does that mean? You just get the package developer to push to Atmosphere every time they release a new version?

I dunno, this seems like a lot of hoops to jump through just to get a working, updated d3 library. You are good at that, but for now I am probably going to just publish my own d3 wrapper package, in the absence of any well-established alternatives. Happy to deprecate this once you get to that point.

**Comment by dandv** [comment]
Right now, it just means running `meteor/publish.sh`, which takes care of versioning and publishes the package on Atmosphere. Pretty painless.

Because most libraries use build scripts of some sort (e.g. Grunt files) to publish updates, pushing to Atmosphere can easily become a zero-effort operation if we [update the Gruntfile](https://github.com/rubaxa/sortable/issues/119) as part of the PR.

**Comment by dandv** [comment]
Ouch re. garilla's hack... deserves a flag - please flag https://atmospherejs.com/garrilla/d3. I'll take a stab at an official d3 integration PR tonight.

**Comment by mizzao** [comment]
How do you flag something? Don't see it anywhere on the page.

**Comment by dandv** [comment]
There should be the word "Flag" right there.

![image](https://cloud.githubusercontent.com/assets/33569/5178185/3aa69770-741c-11e4-8520-1340dcee73e0.png)

**Comment by mizzao** [comment]
I see, had to be logged in. Never mind.
